services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: web
    working_dir: /workspace
    volumes:
      - ./web:/workspace
      - /workspace/node_modules
    environment:
      PUBLIC_API_BASE_URL: http://app:8080
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - internal