services:
  app:
    build:
      context: ./api/modular-monolith
      dockerfile: Dockerfile.dev
    container_name: app
    working_dir: /workspace
    volumes:
      - ./api/modular-monolith:/workspace
    environment:
      - APP_ENV=dev
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    env_file:
      - ./config/aws.env
    depends_on:
      - localstack
    networks:
      - internal
    ports:
      - "8080:8080"

  localstack:
    image: localstack/localstack:3.8
    container_name: localstack
    environment:
      - SERVICES=s3,dynamodb,iam,sts
      - DEBUG=0
      - PERSISTENCE=1
      - AWS_ENDPOINT_URL=http://localhost:4566
    env_file:
      - ./config/aws.env
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init:/etc/localstack/init/ready.d
    networks:
      - internal

volumes:
  localstack-data:

networks:
  internal:
    driver: bridge