services:
  localstack:
    image: localstack/localstack:3.8
    environment:
      - SERVICES=s3,dynamodb,iam,sts
      - DEBUG=0
      - PERSISTENCE=1
      - AWS_ENDPOINT_URL=http://localhost:4566
    env_file:
      - ../config/aws.env
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ../localstack/init:/etc/localstack/init/ready.d
    networks:
      - internal

volumes:
  localstack-data:
