services:
  localstack:
    image: localstack/localstack:3.8
    environment:
      SERVICES: s3,dynamodb,iam,sts
      DEBUG: 0
      PERSISTENCE: 1
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-ap-northeast-1}
      AWS_REGION: ${AWS_REGION:-ap-northeast-1}
      S3_BUCKET: ${S3_BUCKET:-occ-media}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE:-occ-main}
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ../localstack/init:/etc/localstack/init/ready.d
    networks:
      - internal

volumes:
  localstack-data:
